Add needed stuff and fixes for bubble restore process (#20)
Merge branch 'master' of git.bubblev.org:bubblev/bubble into kris/add_support_for_restore_ui

Rename isWaitingRestoring

Use == instead of equals on enums

Use ctime instead of creationTime in backup objects

Fix bin scripts after CR

Merge branch 'master' into kris/add_support_for_restore_ui

# Conflicts:
#	bubble-server/src/main/resources/message_templates/en_US/server/post_auth/ResourceMessages.properties
#	bubble-web

Add missing label

Update web

Merge branch 'master' into kris/add_support_for_restore_ui

# Conflicts:
#	bubble-server/src/main/java/bubble/service/cloud/StandardNetworkService.java
#	bubble-server/src/main/resources/ansible/roles/algo/tasks/main.yml
#	bubble-web

Update web

Use better check if restore is started

Merge branch 'master' into kris/add_support_for_restore_ui

# Conflicts:
#	bubble-server/src/main/java/bubble/service/cloud/StandardNetworkService.java

Init sage node on init self node if needed

Update log message on post copy entities

Update web

Remove another word from host prefixes

Mark restoring node as ready

Add ctime to ticks-stats returned to FE

Merge branch 'master' into kris/add_support_for_restore_ui

# Conflicts:
#	bubble-web

Try resetting progress meter on each new node

Add auth/ready ep in skip auth for restore node

Add more logs of api exception

Update web

Remove some bad host prefixes

Update web

Deploy web if it is included in jar

Merge branch 'master' into kris/add_support_for_restore_ui

Add support for showing latest backup on FE

Merge branch 'master' into kris/add_support_for_restore_ui

Update web

Use proper flag for waiting restoring bubble

Use separate bash to avoid continuing within venv

Start restore monitor on instance when needed

Save iptables in packer instance

Merge branch 'master' into kris/add_support_for_restore_ui

Save iptables before corresponding service restart

Merge branch 'master' into kris/add_support_for_restore_ui

# Conflicts:
#	bubble-server/src/main/java/bubble/server/BubbleConfiguration.java
#	bubble-web

Fix iptables entries again

Echo error to stderr

Fix iptable rules creation

Add back needed tags in algo related ansible tasks

Update web

Merge branch 'master' into kris/add_support_for_restore_ui

# Conflicts:
#	bubble-web

Add new labels and update web

Use network state as restore mode tag

Create full jar with web on full patching

Update first_time_marker file with correct value

Run first time listener for restoring instances also

Merge branch 'master' into kris/add_support_for_restore_ui

# Conflicts:
#	bubble-web

Add new lib to utils pom

Co-authored-by: Jonathan Cobb <jonathan@kyuss.org>
Co-authored-by: Kristijan Mitrovic <kmitrovic@itekako.com>
Reviewed-on: https://git.bubblev.org/bubblev/bubble/pulls/20

diff --git a/bin/bpatchfull b/bin/bpatchfull
--- a/bin/bpatchfull
+++ b/bin/bpatchfull
@@ -45,7 +45,7 @@ else
     echo "Files changed, rebuilding bubble jar: "
     find "./src/main" -type f -newer "$(find "./target" -type f -name "bubble*.jar" | head -1)"
   fi
-  mvn -DskipTests=true -Dcheckstyle.skip=true clean package || die "Error packaging jar"
+  BUBBLE_PRODUCTION=1 mvn -DskipTests=true -Dcheckstyle.skip=true clean package || die "Error packaging jar"
   scp ./target/bubble*.jar ${HOST}:/tmp/bubble.jar || die "Error copying file to remote host ${HOST}"
 fi
 
@@ -55,4 +55,9 @@ if [[ ! -z "${NO_RESTART}" && "${NO_RESTART}" == "norestart" ]] ; then
 else
   echo "Patching and restarting..."
   ssh ${HOST} "cat /tmp/bubble.jar > ~bubble/api/bubble.jar && supervisorctl restart bubble"
+fi
+
+if [[ $(jar tf ./target/bubble*.jar | grep "^site/$") ]] ; then
+  echo "Deploying new web..."
+  ssh ${HOST} "cd ~bubble && jar xf /tmp/bubble.jar site && chown -R bubble:bubble site"
 fi
