simplify patching

diff --git a/bin/bpatch b/bin/bpatch
--- a/bin/bpatch
+++ b/bin/bpatch
@@ -11,12 +11,8 @@
 #  norestart        : If present, do not restart the API server after updating the jar file
 #
 # Patch the bubble.jar on a remote node.
-# This script only works if the only classes that have changed are in the bubble-server codebase.
-# If other classes have changed, use bpatchfull
 #
-# You install the JDK on the remote node first: apt install openjdk-11-jdk-headless
-#
-# Environment variables:
+# Environment variables
 #
 #  BUBBLE_SSH_PORT  : SSH port, default is 1202
 #
@@ -24,7 +20,7 @@ SCRIPT="${0}"
 SCRIPT_DIR="$(cd "$(dirname "${SCRIPT}")" && pwd)"
 . "${SCRIPT_DIR}"/bubble_common
 
-HOST=${1:?no host provided}
+HOST="${1:?no host provided}"
 NO_RESTART=${2}
 validate_user_at_host "${HOST}"
 
@@ -38,15 +34,35 @@ if [[ ! -d "${BUBBLE_SERVER_DIR}" ]] ; then
 fi
 cd "${BUBBLE_SERVER_DIR}" || die "Error changing to ${BUBBLE_SERVER_DIR} directory"
 
-mvn -DskipTests=true -Dcheckstyle.skip=true compile && \
-  rsync ''"$(which ssh)"' -p '"${BUBBLE_SSH_PORT}"'' -avzc ./target/classes ${HOST}:/tmp/ \
-  | egrep -v '*/$' \
-  || die "Error recompiling classes"
+ANY_JAR=$(find "./target" -type f -name "bubble*.jar" | grep -v full | head -1 | wc -l | tr -d ' ')
+if [[ ${ANY_JAR} -eq 0 ]] ; then
+  ANY_CHANGES=1
+else
+  ANY_CHANGES=$(find "./src/main" -type f -newer "$(find "./target" -type f -name "bubble*.jar" | grep -v full | head -1)" | wc -l | tr -d ' ')
+fi
+if [[ ${ANY_CHANGES} -eq 0 ]] ; then
+  echo "No changes, not repackaging jar, copying to ${HOST} ..."
+  scp -P ${BUBBLE_SSH_PORT} "$(find "./target" -type f -name "bubble*.jar" | grep -v full | head -1)" ${HOST}:/tmp/bubble.jar || die "Error copying file to remote host ${HOST}"
+else
+  if [[ ${ANY_JAR} -eq 0 ]] ; then
+    echo "No bubble jar file found, rebuilding, then copying to ${HOST} ..."
+  else
+    echo "Files changed (rebuilding jar, then copying to ${HOST}) ..."
+    find "./src/main" -type f -newer "$(find "./target" -type f -name "bubble*.jar" | head -1)"
+  fi
+  BUBBLE_PRODUCTION=1 mvn -DskipTests=true -Dcheckstyle.skip=true -Pproduction clean package || die "Error packaging jar"
+  scp -P ${BUBBLE_SSH_PORT} "$(find "./target" -type f -name "bubble*.jar" | grep -v full | head -1)" ${HOST}:/tmp/bubble.jar || die "Error copying file to remote host ${HOST}"
+fi
 
 if [[ ! -z "${NO_RESTART}" && "${NO_RESTART}" == "norestart" ]] ; then
   echo "Patching but not restarting: ${HOST} ..."
-  ssh -p ${BUBBLE_SSH_PORT} ${HOST} "cd /tmp && cp ~bubble/api/bubble.jar . && cd classes && jar uvf ../bubble.jar . | egrep -v '*/\(*' && cat ../bubble.jar > ~bubble/api/bubble.jar" || die "Error patching remote jar"
+  ssh -p ${BUBBLE_SSH_PORT} ${HOST} "cat /tmp/bubble.jar > ~bubble/api/bubble.jar"
 else
   echo "Patching and restarting: ${HOST} ..."
-  ssh -p ${BUBBLE_SSH_PORT} ${HOST} "cd /tmp && cp ~bubble/api/bubble.jar . && cd classes && jar uvf ../bubble.jar . | egrep -v '*/\(*' && cat ../bubble.jar > ~bubble/api/bubble.jar && supervisorctl restart bubble" || die "Error patching remote jar"
+  ssh -p ${BUBBLE_SSH_PORT} ${HOST} "cat /tmp/bubble.jar > ~bubble/api/bubble.jar && supervisorctl restart bubble"
+fi
+
+if unzip -Z -1 ./target/bubble*.jar | grep -q "^site/$" ; then
+  echo "Deploying new web: ${HOST} ..."
+  ssh -p ${BUBBLE_SSH_PORT} ${HOST} "cd ~bubble && unzip -q -o /tmp/bubble.jar 'site/*' && chown -R bubble:bubble site"
 fi
