validate user@host for bpatch and bpatchfull commands. clean up shell scripts.

diff --git a/bin/bpatch b/bin/bpatch
--- a/bin/bpatch
+++ b/bin/bpatch
@@ -21,21 +21,18 @@
 #  BUBBLE_SSH_PORT  : SSH port, default is 1202
 #
 SCRIPT="${0}"
-SCRIPT_DIR=$(cd $(dirname ${SCRIPT}) && pwd)
-. ${SCRIPT_DIR}/bubble_common
+SCRIPT_DIR="$(cd "$(dirname "${SCRIPT}")" && pwd)"
+. "${SCRIPT_DIR}"/bubble_common
 
 HOST=${1:?no host provided}
 NO_RESTART=${2}
-
-if [[ -z "$(echo "${HOST}" | tr -cd '[:alnum:].-')" ]] ; then
-  die "invalid host: ${HOST}"
-fi
+validate_user_at_host "${HOST}"
 
 BUBBLE_SERVER_DIR="${SCRIPT_DIR}/../bubble-server"
 if [[ ! -d "${BUBBLE_SERVER_DIR}" ]] ; then
   die "bubble-server dir not found: ${BUBBLE_SERVER_DIR}"
 fi
-cd ${BUBBLE_SERVER_DIR}
+cd "${BUBBLE_SERVER_DIR}" || die "Error changing to ${BUBBLE_SERVER_DIR} directory"
 
 mvn -DskipTests=true -Dcheckstyle.skip=true compile && rsync -avzc ./target/classes ${HOST}:/tmp/ | egrep -v '*/$' || die "Error recompiling classes"
 
diff --git a/bin/bpatchfull b/bin/bpatchfull
--- a/bin/bpatchfull
+++ b/bin/bpatchfull
@@ -18,15 +18,12 @@
 #  BUBBLE_SSH_PORT  : SSH port, default is 1202
 #
 SCRIPT="${0}"
-SCRIPT_DIR=$(cd $(dirname ${SCRIPT}) && pwd)
-. ${SCRIPT_DIR}/bubble_common
+SCRIPT_DIR="$(cd "$(dirname "${SCRIPT}")" && pwd)"
+. "${SCRIPT_DIR}"/bubble_common
 
 HOST="${1:?no host provided}"
 NO_RESTART=${2}
-
-if [[ -z "$(echo "${HOST}" | tr -cd '[:alnum:].-')" ]] ; then
-  die "invalid host: ${HOST}"
-fi
+validate_user_at_host "${HOST}"
 
 if [[ -z "${BUBBLE_SSH_PORT}" ]] ; then
   BUBBLE_SSH_PORT="1202"
@@ -36,7 +33,7 @@ BUBBLE_SERVER_DIR="${SCRIPT_DIR}/../bubble-server"
 if [[ ! -d "${BUBBLE_SERVER_DIR}" ]] ; then
   die "bubble-server dir not found: ${BUBBLE_SERVER_DIR}"
 fi
-cd ${BUBBLE_SERVER_DIR}
+cd "${BUBBLE_SERVER_DIR}" || die "Error changing to ${BUBBLE_SERVER_DIR} directory"
 
 ANY_JAR=$(find "./target" -type f -name "bubble*.jar" | head -1 | wc -l | tr -d ' ')
 if [[ ${ANY_JAR} -eq 0 ]] ; then
