allow running without env file

diff --git a/bin/bubble b/bin/bubble
--- a/bin/bubble
+++ b/bin/bubble
@@ -65,7 +65,7 @@ if [[ -z "${BUBBLE_ENV}" ]] ; then
   elif [[ -f "/home/bubble/api/bubble.env" ]] ; then
     BUBBLE_ENV="/home/bubble/api/bubble.env"
   else
-    die "bubble environment file not found"
+    echo 1>&2 "Warning: bubble environment file not found"
   fi
 fi
 
