fix bugs in reset script

diff --git a/bin/reset_bubble_full b/bin/reset_bubble_full
--- a/bin/reset_bubble_full
+++ b/bin/reset_bubble_full
@@ -14,7 +14,7 @@ SELF_NODE_JSON="${HOME}/self_node.json"
 BUBBLE_VERSIONS_FILE="${HOME}/bubble_versions.properties"
 
 BUBBLE_LOCAL_STORAGE_DIR_DEFAULT=".bubble_local_storage"
-BUBBLE_LOCAL_STORAGE_DIR="$("${SCRIPT_DIR}/bin/bconst" bubble.cloud.storage.local.LocalStorageDriver.BUBBLE_LOCAL_STORAGE_DIR)"
+BUBBLE_LOCAL_STORAGE_DIR="$("${SCRIPT_DIR}/bconst" bubble.cloud.storage.local.LocalStorageDriver.BUBBLE_LOCAL_STORAGE_DIR)"
 if [[ -z ${BUBBLE_LOCAL_STORAGE_DIR} ]] ; then
     echo "Error determining Bubble LocalStorage directory, using default: ${BUBBLE_LOCAL_STORAGE_DIR_DEFAULT}"
     BUBBLE_LOCAL_STORAGE_DIR=${BUBBLE_LOCAL_STORAGE_DIR_DEFAULT}
@@ -22,7 +22,7 @@ fi
 BUBBLE_LOCAL_STORAGE_DIR="${HOME}/${BUBBLE_LOCAL_STORAGE_DIR}"
 
 BUBBLE_CLOUD_DATA_DIR_DEFAULT="bubble_cloudServiceData"
-BUBBLE_CLOUD_DATA_DIR="$("${SCRIPT_DIR}/bin/bconst" bubble.ApiConstants.BUBBLE_CLOUD_SERVICE_DATA)"
+BUBBLE_CLOUD_DATA_DIR="$("${SCRIPT_DIR}/bconst" bubble.ApiConstants.BUBBLE_CLOUD_SERVICE_DATA)"
 if [[ -z ${BUBBLE_CLOUD_DATA_DIR} ]] ; then
     echo "Error determining Bubble Cloud Service Data directory, using default: "
     BUBBLE_CLOUD_DATA_DIR=${BUBBLE_CLOUD_DATA_DIR_DEFAULT}
@@ -41,7 +41,6 @@ echo "> removed: ${BUBBLE_LOCAL_STORAGE_DIR}"
 rm -rf "${BUBBLE_CLOUD_DATA_DIR}" || die "Error removing ${BUBBLE_CLOUD_DATA_DIR}"
 echo "> removed: ${BUBBLE_CLOUD_DATA_DIR}"
 
-dropdb bubble || die "Error dropping bubble database"
-echo "> dropped database: bubble"
+dropdb bubble && echo "> dropped database: bubble" || echo "! error: dropping bubble database"
 
 echo "+++ Bubble Reset Complete"
