fixes to ubuntu scripts

diff --git a/bin/ubuntu_connect_bubble b/bin/ubuntu_connect_bubble
--- a/bin/ubuntu_connect_bubble
+++ b/bin/ubuntu_connect_bubble
@@ -37,6 +37,9 @@ function die() {
   exit 1
 }
 
+# from https://stackoverflow.com/a/34407620
+function uriencode { jq -nr --arg v "$1" '$v|@uri'; }
+
 SCRIPT_DIR="$(cd "$(dirname "${0}")" && pwd)"
 
 if [[ -z "$(which wg)" ]]; then
@@ -129,6 +132,10 @@ if [[ $(bgetn me/devices | grep -c "${DEVICE_NAME}") -eq 0 ]]; then
   rm -f "${VPN_FILE}" "${CERT_FILE}" || die "Error removing obsolete vpn.conf and cert files"
 else
   echo "Device already registered: ${DEVICE_NAME}"
+  if [[ ! -f "${BUBBLE_DIR}/device.json" ]] ; then
+    echo "Downloading device.json file ..."
+    bget "me/devices/$(uriencode "${DEVICE_NAME}")" > "${BUBBLE_DIR}/device.json" || die "Error downloading device JSON file"
+  fi
 fi
 
 # Do we have both a cert file and a vpn.conf? If so, we are done
@@ -143,8 +150,19 @@ if [[ ! -s "${VPN_FILE}" ]]; then
   bget "me/devices/${DEVICE_NAME}/vpn/vpn.conf" --raw >"${VPN_FILE}" || die "Error downloading vpn.conf file"
 fi
 
-echo "Marking ${BUBBLE_HOST} as current Bubble ..."
-cd "${BUBBLE_DEVICE_BASE}" && ln -sf "${BUBBLE_HOST}" current || die "Error creating symlink ${BUBBLE_DEVICE_BASE}/current -> ${BUBBLE_DEVICE_BASE}/${BUBBLE_HOST}"
+CURRENT_DEVICE_DIR="${BUBBLE_DEVICE_BASE}/current"
+CREATE_CURRENT_SYMLINK=0
+if [[ -e "${CURRENT_DEVICE_DIR}" ]] ; then
+  if [[ "$(basename "$(readlink -f "${CURRENT_DEVICE_DIR}")")" != "${BUBBLE_HOST}" ]] ; then
+    CREATE_CURRENT_SYMLINK=1
+  fi
+else
+  CREATE_CURRENT_SYMLINK=1
+fi
+if [[ ${CREATE_CURRENT_SYMLINK} -eq 1 ]] ; then
+  echo "Marking ${BUBBLE_HOST} as current Bubble (cd ${BUBBLE_DEVICE_BASE} && ln -sf ${BUBBLE_HOST} current)..."
+  cd "${BUBBLE_DEVICE_BASE}" && ln -sf "${BUBBLE_HOST}" current || die "Error creating symlink ${BUBBLE_DEVICE_BASE}/current -> ${BUBBLE_DEVICE_BASE}/${BUBBLE_HOST}"
+fi
 
 CERTS_DIR=/usr/share/ca-certificates/extra
 if [[ ! -d "${CERTS_DIR}" ]] ; then
diff --git a/bin/ubuntu_disconnect_bubble b/bin/ubuntu_disconnect_bubble
--- a/bin/ubuntu_disconnect_bubble
+++ b/bin/ubuntu_disconnect_bubble
@@ -58,6 +58,13 @@ if [[ ${DO_DELETE} -eq 0 ]]; then
   exit 0
 fi
 
+if [[ -z "$(which bget)" ]]; then
+  export PATH=${PATH}:${SCRIPT_DIR}
+  if [[ -z "$(which bget)" ]]; then
+    die "bget command not found, even after adding ${SCRIPT_DIR} to PATH"
+  fi
+fi
+
 BUBBLE_DEVICE_BASE="${HOME}/bubble_devices"
 DEVICE_JSON_FILE="${BUBBLE_DEVICE_BASE}/current/device.json"
 if [[ ! -f "${DEVICE_JSON_FILE}" ]]; then
@@ -70,19 +77,15 @@ if [[ -z "${CURRENT_DEVICE_JSON}" ]] ; then
 fi
 BUBBLE_HOST="$(basename "$(readlink -f "${CURRENT_DEVICE_DIR}")")"
 BUBBLE_DIR="${BUBBLE_DEVICE_BASE}/${BUBBLE_HOST}"
-
-if [[ -d "${BUBBLE_DIR}" ]]; then
-  echo "Removing directory: ${BUBBLE_DIR}"
-  rm -rf "${BUBBLE_DIR}" || die "Error removing ${BUBBLE_DIR}"
-fi
-echo "Removing symlink: ${BUBBLE_DEVICE_BASE}/current"
-rm -f "${BUBBLE_DEVICE_BASE}/current" || die "Error removing ${BUBBLE_DEVICE_BASE}/current"
+CERT_FILE="${BUBBLE_DIR}"/bubble-${BUBBLE_HOST}.crt
 
 CERTS_DIR=/usr/share/ca-certificates/extra
 CERT_DEST="${CERTS_DIR}/$(basename "${CERT_FILE}")"
 if [[ -f "${CERT_DEST}" ]]; then
   echo "Removing certificate: ${CERT_DEST} ..."
-  rm -f "${CERT_DEST}"
+  sudo rm -f "${CERT_DEST}"
+else
+  echo "Certificate not installed, not removing: ${CERT_DEST}"
 fi
 
 echo "
@@ -136,6 +139,13 @@ bget me | jq .email > /dev/null || die "Error logging into Bubble with API: ${BU
 
 echo "Deleting device: ${DEVICE_NAME}"
 bdelete "me/devices/${DEVICE_UUID}" || die "Error deleting device: ${DEVICE_NAME} (uuid ${DEVICE_UUID})"
+
+if [[ -d "${BUBBLE_DIR}" ]]; then
+  echo "Removing directory: ${BUBBLE_DIR}"
+  rm -rf "${BUBBLE_DIR}" || die "Error removing ${BUBBLE_DIR}"
+fi
+echo "Removing symlink: ${BUBBLE_DEVICE_BASE}/current"
+rm -f "${BUBBLE_DEVICE_BASE}/current" || die "Error removing ${BUBBLE_DEVICE_BASE}/current"
 
 echo "
 ==============================================================
