build image before checking version, fix test

diff --git a/bin/jenkins/push_docker b/bin/jenkins/push_docker
--- a/bin/jenkins/push_docker
+++ b/bin/jenkins/push_docker
@@ -42,16 +42,18 @@ if [[ -z "${VERSION}" ]] ; then
 fi
 echo "Found Bubble version ${VERSION}"
 
-echo "Checking to see if this version already exists on dockerhub..."
+echo "Building docker bubble version ${VERSION} ..."
+BUBBLE_DOCKER="${BUBBLE_DIR}/docker/bubble.sh"
+${BUBBLE_DOCKER} build || die "Error building docker image"
+
+echo "Checking to see if version ${VERSION} already exists on dockerhub..."
 if docker manifest inspect "getbubble/launcher:${VERSION}" > /dev/null 2> /dev/null ; then
-  echo "Version already exists on dockerhub, not re-publishing: ${VERSION}"
+  echo "Version ${VERSION} already exists on dockerhub, not re-publishing"
   exit 0
 fi
 
-echo "Version does not exist on dockerhub, building and pushing it..."
+echo "Version does not exist on dockerhub, pushing it..."
 
-BUBBLE_DOCKER="${BUBBLE_DIR}/docker/bubble.sh"
-${BUBBLE_DOCKER} build || die "Error building docker image"
 ${BUBBLE_DOCKER} push || die "Error pushing docker image"
 
 echo "Successfully pushed to dockerhub: ${VERSION}"
